// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PE5du1YEy_ELUANQctLrhvQ_QiQaQps',
    appId: '1:584589240750:web:3d4baf055865257bed803f',
    messagingSenderId: '584589240750',
    projectId: 'sign-7b1d8',
    authDomain: 'sign-7b1d8.firebaseapp.com',
    storageBucket: 'sign-7b1d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRuoavlQqAhYqMhzs9R8l_LIuxUM-foUU',
    appId: '1:584589240750:android:7f96e5059dfe8805ed803f',
    messagingSenderId: '584589240750',
    projectId: 'sign-7b1d8',
    storageBucket: 'sign-7b1d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKyzGcFRlpXkE7RJ10KSlB33JdqO2YnQ',
    appId: '1:584589240750:ios:357a9cf328362ffeed803f',
    messagingSenderId: '584589240750',
    projectId: 'sign-7b1d8',
    storageBucket: 'sign-7b1d8.firebasestorage.app',
    androidClientId: '584589240750-ofe4go6i9tj9od66i43pltj6s6v8ecrr.apps.googleusercontent.com',
    iosClientId: '584589240750-gns3q7krst2vg7r40hs2s3umrr1d3b16.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsKyzGcFRlpXkE7RJ10KSlB33JdqO2YnQ',
    appId: '1:584589240750:ios:357a9cf328362ffeed803f',
    messagingSenderId: '584589240750',
    projectId: 'sign-7b1d8',
    storageBucket: 'sign-7b1d8.firebasestorage.app',
    androidClientId: '584589240750-ofe4go6i9tj9od66i43pltj6s6v8ecrr.apps.googleusercontent.com',
    iosClientId: '584589240750-gns3q7krst2vg7r40hs2s3umrr1d3b16.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5PE5du1YEy_ELUANQctLrhvQ_QiQaQps',
    appId: '1:584589240750:web:0af2496e67536febed803f',
    messagingSenderId: '584589240750',
    projectId: 'sign-7b1d8',
    authDomain: 'sign-7b1d8.firebaseapp.com',
    storageBucket: 'sign-7b1d8.firebasestorage.app',
  );

}